spring:
  application:
    name: TFG-cultura-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:root@localhost:27018/cultura_db?authSource=admin}
      database: ${MONGO_DB:cultura_db}

server:
  port: ${PORT:8080}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}
  seed-enabled: ${SEED_ENABLED:true}
  jwt:
    secret: ${JWT_SECRET:NqFALt52zysAic5Ks57tqYEFPIcDGVMZ}
    expiration: ${JWT_EXPIRATION:86400000}
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}
    enabled: ${CLOUDINARY_ENABLED:true}
  admin-roles: [COORDINADOR, SECRETARIO, ENCARGADO, COLABORADOR]

springdoc:
  swagger-ui:
    path: /api/docs
    doc-expansion: none
    default-models-expand-depth: -1

sonar:
  coverage:
    exclusions: "**/config/**,**/MongoConfiguration.java,**/DatabaseSeeder.java"