spring.devtools.restart.enabled=true
# Solo recarga cuando guarda archivos (no por polling continuo)
spring.devtools.restart.poll-interval=3000
spring.devtools.restart.quiet-period=1000
# Excluye archivos que no requieren restart
spring.devtools.restart.exclude=static/**,public/**,templates/**