spring.application.name=TFG-cultura-api
spring.data.mongodb.uri=${MONGODB_URI:mongodb://root:root@localhost:27018/cultura_db?authSource=admin}
spring.data.mongodb.database=${MONGO_DB:cultura_db}
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
server.port=${PORT:8080}
springdoc.swagger-ui.path=/api/docs
sonar.coverage.exclusions=**/config/**,**/MongoConfiguration.java,**/DatabaseSeeder.java
# Seeder
app.seed.enabled=${SEED_ENABLED:true}
# JWT
jwt.secret=${JWT_SECRET:NqFALt52zysAic5Ks57tqYEFPIcDGVMZ}
jwt.expiration=${JWT_EXPIRATION:86400000}
# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
cloudinary.enabled=true