spring.application.name=TFG-cultura-api
spring.data.mongodb.uri=${MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongo:27017/mydatabase?authSource=admin}}
spring.mongodb.uri=${MONGODB_URI:${SPRING_MONGODB_URI:${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongo:27017/mydatabase?authSource=admin}}}
spring.data.mongodb.database=${MONGODB_DATABASE:${SPRING_DATA_MONGODB_DATABASE:mydatabase}}
spring.mongodb.database=${MONGODB_DATABASE:${SPRING_MONGODB_DATABASE:${SPRING_DATA_MONGODB_DATABASE:mydatabase}}}
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
spring.docker.compose.enabled=false
server.port=${PORT:8080}
springdoc.swagger-ui.path=/api/docs