name: Checkstyle Backend CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27018:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: test

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
        
      - name: Make mvnw executable
        run: chmod +x mvnw
        working-directory: backend

      - name: Run Checkstyle
        run: ./mvnw clean verify -Dspring.profiles.active=test